# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  container:
    docker:
      - image: cimg/base:current
  linux-vm:
    machine:
      image: ubuntu-2004:current


        # Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    executor: container
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  second-job:
    executor: linux-vm
    steps:
      - checkout
      - run: echo "Hello Circle CI"



workflows:
  say-hello-workflow: # this can be anything
    jobs:
      - say-hello
      - second-job

  second-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              only:
                - dev
                - /test-.*/
